version: '3.8'

services:
  database:
    image: postgres:13.4
    container_name: hansel-database
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - hansel-network
    logging:
      driver: journald
    expose:
      - '${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    image: hansel-backend
    container_name: hansel-backend
    restart: always
    depends_on:
      - database
    networks:
      - hansel-network
    logging:
      driver: journald
    expose:
      - '${SERVER_PORT}'
    environment:
      GO_ENV: production
      SERVER_PORT: ${SERVER_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: disable

  reverse-proxy:
    image: hansel-reverse-proxy
    container_name: hansel-reverse-proxy
    restart: always
    depends_on:
      - backend
    networks:
      - hansel-network
    ports:
      - "10000:10000"
      - "9901:9901"

networks:
  hansel-network:
