# To build a Docker image from this file, run from the root directory:
# docker build -f deployment/Dockerfile-backend-proxy -t hansel-backend-proxy .

# Base image
FROM envoyproxy/envoy:v1.19.1

# Environment variables
ENV APP_ROOT /backend-proxy

# Copy configuration into container
RUN mkdir --parents $APP_ROOT
WORKDIR $APP_ROOT
COPY deployment/envoy.yaml .

# Default command
CMD ["sh", "-c", "/usr/local/bin/envoy -c envoy.yaml"]
