# To build a Docker image from this file, run from the root directory:
# docker build -f deployment/Dockerfile-frontend -t hansel-frontend .

# Base image
FROM node:16.9.1

# Install Protocol Buffer compiler
RUN apt-get update
RUN apt-get install -y protobuf-compiler

# Install simple HTTP server for serving static content
RUN npm install -g http-server

# Environment variables
ENV API_SPECS_ROOT /api-specs
ENV APP_ROOT /frontend

# Copy API specs into container
RUN mkdir --parents $API_SPECS_ROOT
WORKDIR $API_SPECS_ROOT
COPY api-specs .

# Copy source code into container
RUN mkdir --parents $APP_ROOT
WORKDIR $APP_ROOT
COPY frontend .

# Install dependencies
RUN npm ci

# Add a script to be executed every time the container starts
COPY deployment/entrypoint-scripts/frontend.sh /usr/bin/
RUN chmod +x /usr/bin/frontend.sh
ENTRYPOINT ["frontend.sh"]

# Expose port 8080
EXPOSE 8080

# Default command
CMD ["sh", "-c", "http-server dist"]
