# To build a Docker image from this file, run from the root directory:
# docker build -f deployment/Dockerfile-backend -t hansel-backend .

# Base image
FROM golang:1.17.1

# Install Protocol Buffer compiler
RUN apt-get update
RUN apt-get install -y protobuf-compiler
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.27.1
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1.0

# Environment variables
ENV API_SPECS_ROOT /api-specs
ENV APP_ROOT /backend

# Copy API specs into container
RUN mkdir --parents $API_SPECS_ROOT
WORKDIR $API_SPECS_ROOT
COPY api-specs .

# Copy source code into container
RUN mkdir --parents $APP_ROOT
WORKDIR $APP_ROOT
COPY backend .

# Add a script to be executed every time the container starts
COPY deployment/entrypoint-scripts/backend.sh /usr/bin/
RUN chmod +x /usr/bin/backend.sh
ENTRYPOINT ["backend.sh"]

# Expose port 8000
EXPOSE 8000

# Default command
CMD ["sh", "-c", "make run"]
