version: '3.8'

services:
  database:
    image: postgres:13.4
    container_name: hansel-database
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - hansel-network
    logging:
      driver: journald
    expose:
      - '${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    image: hansel-backend
    container_name: hansel-backend
    restart: always
    depends_on:
      - database
    networks:
      - hansel-network
    logging:
      driver: journald
    expose:
      - '8000'
    environment:
      GO_ENV: production
      SERVER_PORT: 8000
      SECRET_KEY: ${SECRET_KEY}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: disable

  backend-proxy:
    image: hansel-backend-proxy
    container_name: hansel-backend-proxy
    restart: always
    depends_on:
      - backend
    networks:
      - hansel-network
    logging:
      driver: journald
    ports:
      - '10000:10000'

  frontend:
    image: hansel-frontend
    container_name: hansel-frontend
    restart: always
    depends_on:
      - backend-proxy
    networks:
      - hansel-network
    logging:
      driver: journald
    ports:
      - '80:80'
      - '443:443'
    environment:
      NODE_ENV: production
      VUE_APP_SERVER_URL: hansel-backend
      VUE_APP_SERVER_PORT: 10000
      VUE_APP_GOOGLE_API_KEY: ${VUE_APP_GOOGLE_API_KEY}
      VUE_APP_GOOGLE_ANALYTICS_ID: ${VUE_APP_GOOGLE_ANALYTICS_ID}

networks:
  hansel-network:
