# To build a Docker image from this file, run from the root directory:
# docker build -f deployment/Dockerfile-backend -t hansel-backend .

# Base image
FROM golang:1.17.1

# Environment variables
ENV APP_ROOT /backend

# Copy source code into container
RUN mkdir --parents $APP_ROOT
WORKDIR $APP_ROOT
COPY backend .

# Add a script to be executed every time the container starts.
COPY deployment/entrypoint-scripts/backend.sh /usr/bin/
RUN chmod +x /usr/bin/backend.sh
ENTRYPOINT ["backend.sh"]

# Expose port 8000
EXPOSE 8000

# Default command
CMD ["sh", "-c", "make run"]
