name: Build backend Docker image

on:
  push:
    tags:
      - v*
    branches:
      - master
  # For testing
      - ian/add-deployment-cd-job

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hansel-backend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: hansel-app
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/Dockerfile-backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
