name: gosec

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  gosec:
    name: check
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        working-directory: backend
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          gosec ./...
