name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - name: Build files
        run: npm run build
        working-directory: frontend
      - name: Publish to GH pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          git --work-tree dist add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin gh-pages --force
        working-directory: frontend
