name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: Pre-build configuration
        run: |
          cp frontend/.env.sample frontend/.env
      - name: Build files
        run: |
          flutter config --enable-web
          flutter pub get
          flutter build web --release
        shell: bash
        working-directory: frontend
      - name: Post-build configuration
        run: |
          repo_name=${{ github.event.repository.name }}
          sed -i 's#<base href="/">#<base href="/'"$repo_name"'/">#g' frontend/build/web/index.html
      - name: Publish to GH pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git --work-tree build/web add --all
          git commit -m "Automatic deployment by github-actions"
          git push origin HEAD:gh-pages --force
        shell: bash
        working-directory: frontend
